-- https://github.com/nvim-treesitter/nvim-treesitter/blob/master/CONTRIBUTING.md
-- https://tonsky.me/blog/syntax-highlighting/
local M = {}
local p = {
--stylua: ignore start
  bg      = "#3b3228", --background
  bg95    = "#43392d", --barely use! near-invisible, subtle highlighting
  bg75    = "#4c4134", --comments,
  bg25    = "#6b6055",
  altbg   = "#5d4f40",
  sand    = "#c1a387",
  fg      = "#afd2e9",
  cyan    = "#3eccbe",
  scarlet = "#e86045", --variables
  orange  = "#e68d53", --integers
  saffron = "#f8e2a0", --selection
  moss    = "#92a650",
  celadon = "#ace1af",
  grey    = "#868686",
}
--stylua: ignore end
function M.setup()
  vim.cmd("highlight clear")
  vim.o.background = "dark"
  local hl_groups = {
    Normal = { fg = p.fg, bg = p.bg },

    MiniHiPatternsBase00 = { bg = "#3b3228" },
    MiniHiPatternsBase01 = { bg = "#4c4134" },
    MiniHiPatternsBase02 = { bg = "#5d4f40" },
    MiniHiPatternsBase03 = { bg = "#6b6055" },
    MiniHiPatternsBase04 = { bg = "#c1a387" },
    MiniHiPatternsBase05 = { bg = "#afd2e9" },
    MiniHiPatternsBase06 = { bg = "#FF00FF" },
    MiniHiPatternsBase07 = { bg = "#00FF00" },
    MiniHiPatternsBase08 = { bg = "#e86045" },
    MiniHiPatternsBase09 = { bg = "#e68d53" },
    MiniHiPatternsBase0A = { bg = "#f8e2a0" },
    MiniHiPatternsBase0B = { bg = "#92a650" },
    MiniHiPatternsBase0C = { bg = "#ace1af" },
    MiniHiPatternsBase0D = { bg = "#3eccbe" },
    MiniHiPatternsBase0E = { bg = "#FF0000" },
    MiniHiPatternsBase0F = { bg = "#f8e2a0" },
    --  ComplMatchIns  = {},
    --  Conceal        = {},
    --  CurSearch      = {},
    --  Cursor         = {},
    --  CursorColumn   = {},
    --  CursorIM       = {},
    CursorLine = { bg = p.bg75 },
    CursorLineNr = { fg = p.sand, bg = p.bg75 },
    --  CursorLineFold = {},
    CursorLineSign = { bg = p.bg75 },
    DiffAdd = { fg = p.moss },
    DiffChange = { fg = p.orange },
    DiffDelete = { fg = p.scarlet },
    --  DiffText       = {},
    --  DiffTextAdd    = {},
    --  Directory      = {},
    --  EndOfBuffer    = {},
    ErrorMsg = { fg = p.scarlet },
    FloatBorder = { fg = p.sand, bg = p.bg },
    --  FoldColumn     = {},
    --  Folded         = {},
    --  IncSearch      = {},
    --  lCursor        = {},
    LineNr = { bg = p.bg, fg = p.altbg },
    LineNrAbove = { bg = p.bg, fg = p.altbg },
    LineNrBelow = { bg = p.bg, fg = p.altbg },
    --  MatchParen     = {},
    --  ModeMsg        = {},
    --  MoreMsg        = {},
    --  MsgArea        = {},
    --  MsgSeparator   = {},
    --  NonText        = {},
    --  NormalFloat    = {},
    --  NormalNC       = {},
    --  OkMsg          = {},
    --  Pmenu          = {},
    --  PmenuExtra     = {},
    --  PmenuExtraSel  = {},
    --  PmenuKind      = {},
    --  PmenuKindSel   = {},
    --  PmenuMatch     = {},
    --  PmenuMatchSel  = {},
    --  PmenuSbar      = {},
    --  PmenuSel       = {},
    --  PmenuThumb     = {},
    --  Question       = {},
    --  QuickFixLine   = {},
    --  Search         = {},
    SignColumn = { bg = p.bg },
    --  SpecialKey     = {},
    --  SpellBad       = {},
    --  SpellCap       = {},
    --  SpellLocal     = {},
    --  SpellRare      = {},
    --  StatusLine     = {},
    --  StatusLineNC   = {},
    --  StderrMsg      = {},
    --  StdoutMsg      = {},
    --  Substitute     = {},
    --  TabLine        = {},
    --  TabLineFill    = {},
    --  TabLineSel     = {},
    --  TermCursor     = {},
    --  TermCursorNC   = {},
    --  Title          = {},
    --  VertSplit      = {},
    --  Visual         = {},
    --  VisualNOS      = {},
    --  WarningMsg     = {},
    --  Whitespace     = {},
    --  WildMenu       = {},
    --  WinBar         = {},
    --  WinBarNC       = {},
    --  WinSeparator   = {},

    --Syntax -----------------------------------
    Comment = { fg = p.bg25 },
    Constant = { fg = p.fg },
    String = { fg = p.moss },
    -- Character       = {},
    Number = { fg = p.orange },
    Boolean = { fg = p.orange },
    Float = { fg = p.orange },
    Identifier = { fg = p.fg },
    Function = { fg = p.fg },
    -- Statement = { fg = p.sand },
    -- Conditional = { fg = p.scarlet },
    -- Repeat          = {},
    -- Label = { fg = p.fg },
    Operator = { fg = p.fg },
    --  Keyword        = {},
    --  Exception      = {},
    -- PreProc         = {},
    --  Include        = {},
    --  Define         = {},
    --  Macro          = {},
    -- PreCondit       = {},
    -- Type            = {},
    -- StorageClass    = {},
    --  Structure      = {},
    -- Typedef         = {},
    Special = { fg = p.celadon },
    -- SpecialChar     = {  },
    Tag = { fg = p.orange },
    -- Delimiter       = {},
    --  SpecialComment = {},
    --  Debug          = {},
    --  Ignore         = {},
    --  Error          = {},
    --  Todo           = {},
    --treesitter--------------------------------------
    ["@variable"] = { link = "Identifier" },
    --["@variable.builtin"]={},
    --["@variable.parameter"]={},
    --["@variable.parameter.builtin"]={},
    --["@variable.member"]={},
    ["@constant"] = { link = "Constant" },
    --["@constant"]={},
    --["@constant.builtin"]={},
    --["@constant.macro"]={},
    --["@module"]={},
    --["@module.builtin"]={},
    --["@label"]={},
    ["@string"] = { link = "String" },
    --["@string.documentation"]={},
    --["@string.regexp"]={},
    --["@string.escape"]={},
    --["@string.special"]={},
    --["@string.special.symbol"]={},
    --["@string.special.url"]={},
    --["@string.special.path"]={},
    --["@character"]={},
    --["@character.special"]={},
    ["@boolean"] = { link = "Boolean" },
    ["@number"] = { link = "Number" },
    ["@number.float"] = { link = "Float" },
    --["@type"]={},
    --["@type.builtin"]={},
    --["@type.definition"]={},
    --["@attribute"]={},
    --["@attribute.builtin"]={},
    --["@property"]={},
    ["@function"] = { link = "Function" },
    --["@function.builtin"]={},
    --["@function.call"]={},
    --["@function.macro"]={},
    --["@function.method"]={},
    --["@function.method.call"]={},
    --["@constructor"]={},
    --["@operator"]={},
    --["@keyword"]={},
    --["@keyword.coroutine"]={},
    --["@keyword.function"]={},
    --["@keyword.operator"]={},
    --["@keyword.import"]={},
    --["@keyword.type"]={},
    --["@keyword.modifier"]={},
    --["@keyword.repeat"]={},
    --["@keyword.return"]={},
    --["@keyword.debug"]={},
    --["@keyword.exception"]={},
    ["@keyword.conditional"] = { fg = p.sand },
    ["@keyword.conditional.ternary"] = { fg = p.sand },
    --["@keyword.directive"]={},
    --["@keyword.directive.define"]={},
    ["@punctuation.delimiter"] = { fg = p.fg },
    -- ["@punctuation.bracket"]={},
    -- ["@punctuation.special"]={},
    ["@comment"] = { link = "Comment" },
    -- ["@comment.documentation"] = {},
    ["@comment.error"] = { bg = p.scarlet, fg = p.bg }, -- error-type comments (e.g. `ERROR`, `FIXME`, `DEPRECATED`)
    ["@comment.warning"] = { bg = p.orange, fg = p.bg }, -- warning-type comments (e.g. `WARNING`, `FIX`, `HACK`)
    ["@comment.todo"] = { bg = p.saffron, fg = p.bg }, -- todo-type comments (e.g. `TODO`, `WIP`)
    ["@comment.note"] = { bg = p.scarlet, fg = p.bg }, -- note-type comments (e.g. `NOTE`, `INFO`, `XXX`)
    ["@diff.plus"] = { link = "Added" },
    ["@diff.minus"] = { link = "Removed" },
    ["@diff.delta"] = { link = "Changed" },
    ["@tag"] = { link = "Tag" },
    --["@tag.builtin"]={},
    --["@tag.attribute"]={},
    --["@tag.delimiter"]={},
    --Diff--------------------------------------------
    Added = { fg = p.moss },
    Changed = { fg = p.orange },
    Removed = { fg = p.scarlet },
    --
    -- -- Git commit
    --  gitcommitBranch         = {},
    --  gitcommitComment        = {},
    --  gitcommitDiscarded      = {},
    --  gitcommitDiscardedFile  = {},
    --  gitcommitDiscardedType  = {},
    --  gitcommitHeader         = {},
    --  gitcommitOverflow       = {},
    --  gitcommitSelected       = {},
    --  gitcommitSelectedFile   = {},
    --  gitcommitSelectedType   = {},
    --  gitcommitSummary        = {},
    --  gitcommitUnmergedFile   = {},
    --  gitcommitUnmergedType   = {},
    --  gitcommitUntracked      = {},
    --  gitcommitUntrackedFile  = {},

    --Diagnostics----------------------------------------
    DiagnosticError = { fg = p.scarlet },
    DiagnosticWarn = { fg = p.orange },
    DiagnosticInfo = { fg = p.celadon },
    DiagnosticHint = { fg = p.cyan },
    DiagnosticOk = { fg = p.moss },

    -- DiagnosticFloatingError = {},
    -- DiagnosticFloatingHint = {},
    -- DiagnosticFloatingInfo = {},
    -- DiagnosticFloatingOk = {},
    -- DiagnosticFloatingWarn = {},

    DiagnosticSignError = { bg = p.bg, fg = p.scarlet },
    DiagnosticSignWarn = { bg = p.bg, fg = p.orange },
    DiagnosticSignInfo = { bg = p.bg, fg = p.celadon },
    DiagnosticSignHint = { bg = p.bg, fg = p.cyan },
    DiagnosticSignOk = { bg = p.bg, fg = p.moss },

    DiagnosticUnderlineError = { link = "DiagnosticError" },
    DiagnosticUnderlineWarn = { link = "DiagnosticWarn" },
    DiagnosticUnderlineInfo = { link = "DiagnosticInfo" },
    DiagnosticUnderlineOk = { link = "DiagnosticOk" },
    DiagnosticUnderlineHint = { link = "DiagnosticHint" },
    --LSP------------------------------------------------
    --  LspReferenceText              = {},
    --  LspReferenceRead              = {},
    --  LspReferenceWrite             = {},
    --
    --  LspSignatureActiveParameter   = {},
    --
    --  LspCodeLens                   = {},
    --  LspCodeLensSeparator          = {},
    --
    -- -- Built-in snippets
    --  SnippetTabstop                = {},
    --  SnippetTabstopActive          = {},
    --
    -- -- Built-in markdown syntax
    --  markdownH1                    = {},
    --  markdownH2                    = {},
    --  markdownH3                    = {},
    --  markdownH4                    = {},
    --  markdownH5                    = {},
    --  markdownH6                    = {},
    --
    --
    --  MiniDiffSignAdd               = {},
    --  MiniDiffSignChange            = {},
    --  MiniDiffSignDelete            = {},
    --  MiniDiffOverAdd               = {},
    --  MiniDiffOverChange            = {},
    --  MiniDiffOverChangeBuf         = {},
    --  MiniDiffOverContext           = {},
    --  MiniDiffOverContextBuf        = {},
    --  MiniDiffOverDelete            = {},
    --
    --
    MiniHipatternsFixme = { bg = p.scarlet, fg = p.bg },
    MiniHipatternsHack = { bg = p.orange, fg = p.bg },
    MiniHipatternsNote = { bg = p.cyan, fg = p.bg },
    MiniHipatternsTodo = { bg = p.saffron, fg = p.bg },
    --
    --  MiniSurround                  = {},
    --
    -- -- akinsho/bufferline.nvim
    --  BufferLineBuffer              = {},
    --  BufferLineBufferSelected      = {},
    --  BufferLineBufferVisible       = {},
    --  BufferLineCloseButton         = {},
    --  BufferLineCloseButtonSelected = {},
    --  BufferLineCloseButtonVisible  = {},
    --  BufferLineFill                = {},
    --  BufferLineTab                 = {},
    --  BufferLineTabSelected         = {},
    --
    -- -- folke/trouble.nvim
    --  TroubleCount                  = {},
    --  TroubleFoldIcon               = {},
    --  TroubleIndent                 = {},
    --  TroubleLocation               = {},
    --  TroubleSignError              = {},
    --  TroubleSignHint               = {},
    --  TroubleSignInformation        = {},
    --  TroubleSignOther              = {},
    --  TroubleSignWarning            = {},
    --  TroubleText                   = {},
    --  TroubleTextError              = {},
    --  TroubleTextHint               = {},
    --  TroubleTextInformation        = {},
    --  TroubleTextWarning            = {},
    ---folke/which-key.nvim--------------------------------------
    WhichKey = { fg = p.orange },
    WhichKeyNormal = { fg = p.fg, bg = p.bg },
    WhichKeyBorder = { link = "FloatBorder" },
    WhichKeyDesc = { fg = p.fg },
    WhichKeyTitle = { bg = p.bg, fg = p.orange },
    WhichKeySeparator = { fg = p.sand, bg = p.bg },
    WhichKeyGroup = { bg = p.bg, fg = p.celadon },
    --HiPhish/rainbow-delimiters.nvim----------------------------
    RainbowDelimiterBlue = {},
    RainbowDelimiterGreen = {},
    RainbowDelimiterOrange = {},
    RainbowDelimiterRed = { fg = p.scarlet },
    RainbowDelimiterCyan = { fg = p.cyan },
    RainbowDelimiterYellow = { fg = p.saffron },
    RainbowDelimiterViolet = { fg = p.sand },
    --lewis6991/gitsigns.nvim-------------------------------------
    GitSignsAdd = { link = "Added" },
    --  GitSignsAddLn                  = {},
    --  GitSignsAddInline              = {},

    GitSignsChange = { link = "Changed" },
    --  GitSignsChangeLn               = {},
    --  GitSignsChangeInline           = {},

    GitSignsDelete = { link = "Removed" },
    --  GitSignsDeleteLn               = {},
    --  GitSignsDeleteInline           = {},

    --  GitSignsUntracked              = {},
    --  GitSignsUntrackedLn            = {},
    --  GitSignsUntrackedInline        = {},
    --RenderMarkdown----------------------------------------------
    RerMarkdownBullet = { fg = p.moss },
    --  RerMarkdownBullet              = {},
    --  RerMarkdownChecked             = {},
    RerMarkdownCheckedItem = { fg = p.grey, strikethrough = true },
    --  RerMarkdownCode                = {},
    --  RerMarkdownCodeInline          = {},
    --  RerMarkdownDash                = {},
    --  RerMarkdownH1                  = {},
    --  RerMarkdownH1Bg                = {},
    --  RerMarkdownH2                  = {},
    --  RerMarkdownH2Bg                = {},
    --  RerMarkdownH3                  = {},
    --  RerMarkdownH3Bg                = {},
    --  RerMarkdownH4                  = {},
    --  RerMarkdownH4Bg                = {},
    --  RerMarkdownH5                  = {},
    --  RerMarkdownH5Bg                = {},
    --  RerMarkdownH6                  = {},
    --  RerMarkdownH6Bg                = {},
    --  RerMarkdownTodo                = {},
    --  RerMarkdownUnchecked           = {},
    --OXY2DEV/helpview.nvim---------------------------------------
    --  HelpviewHeading1               = {},
    --  HelpviewHeading2               = {},
    --  HelpviewHeading3               = {},
    --  HelpviewHeading4               = {},
    --  HelpviewMentionlink            = {},
    --  HelpviewOptionlink             = {},
    --  HelpviewTaglink                = {},
    --  HelpviewTitle                  = {},
    --

    -- MasonBackdrop                   = { bg   = p.bg },
    -- MasonError                      = { fg   = p.scarlet },
    -- MasonHeader                     = { fg   = p.bg, bg              = p.cyan },
    -- MasonHeaderSecondary            = { fg   = p.bg, bg              = p.cyan },
    -- MasonHeading                    = {},
    -- MasonHighlight                  = {},
    -- MasonHighlightBlock             = {},
    -- MasonHighlightBlockBold         = {},
    -- MasonHighlightBlockBoldSecondary= {},
    -- MasonHighlightBlockSecondary    = {},
    -- MasonHighlightSecondary         = {},
    -- MasonLink                       = {},
    -- MasonMuted                      = {},
    -- MasonMutedBlock                 = {},
    -- MasonMutedBlockBold             = {},
    --stylua: ignore end
  }

  -- hi('MasonHighlight',                   {fg=p.base0F
  -- hi('MasonHighlightBlock',              {fg=p.base00, bg=p.base0F,
  -- hi('MasonHighlightBlockBold',          {link='MasonHeaderSecondary
  -- hi('MasonHighlightBlockBoldSecondary', {link='MasonHeader'},)
  -- hi('MasonHighlightBlockSecondary',     {fg=p.base00, bg=p.base0D,
  -- hi('MasonHighlightSecondary',          {fg=p.base0D,
  -- hi('MasonLink',                        {link='MasonHighlight'},)
  -- hi('MasonMuted',                       {link='Comment'},)
  -- hi('MasonMutedBlock',                  {fg=p.base00, bg=p.base03,
  -- hi('MasonMutedBlockBold',              {fg=p.base00, bg=p.base03,
  -- -- Terminal colors
  -- vim.g.terminal_color_0 = palette.base00
  -- vim.g.terminal_color_1 = palette.base08
  -- vim.g.terminal_color_2 = palette.base0B
  -- vim.g.terminal_color_3 = palette.base0A
  -- vim.g.terminal_color_4 = palette.base0D
  -- vim.g.terminal_color_5 = palette.base0E
  -- vim.g.terminal_color_6 = palette.base0C
  -- vim.g.terminal_color_7 = palette.base05
  -- vim.g.terminal_color_8 = palette.base03
  -- vim.g.terminal_color_9 = palette.base08
  -- vim.g.terminal_color_10 = palette.base0B
  -- vim.g.terminal_color_11 = palette.base0A
  -- vim.g.terminal_color_12 = palette.base0D
  -- vim.g.terminal_color_13 = palette.base0E
  -- vim.g.terminal_color_14 = palette.base0C
  -- vim.g.terminal_color_15 = palette.base07
  for name, hl in pairs(hl_groups) do
    vim.api.nvim_set_hl(0, name, hl)
  end
end
return M
