[[mgr.prepend_keymap]]
on   = [ "c", "m" ]
run  = "plugin chmod"
desc = "Chmod on selected files"
[[mgr.prepend_keymap]]
on   = [ "g", "i" ]
run  = "plugin lazygit"
desc = "run lazygit"
[[mgr.prepend_keymap]]
on   = "R"
run  = "plugin rsync"
desc = "Copy files using rsync"
[[mgr.prepend_keymap]]
on   = [ "u", "d" ]
run  = "plugin restore"
desc = "Restore last deleted files/folders"
[[mgr.prepend_keymap]]
on   = "!"
run  = 'shell "$SHELL" --block'
desc = "Open $SHELL here"
[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"


