[[mgr.prepend_keymap]]
on   = [ "c", "m" ]
run  = "plugin chmod"
desc = "Chmod on selected files"
[[mgr.prepend_keymap]]
on   = [ "g", "i" ]
run  = "plugin lazygit"
desc = "run lazygit"
[[mgr.prepend_keymap]]
on   = "R"
run  = "plugin rsync"
desc = "Copy files using rsync"
