[plugin]
prepend_previewers = [
  { name = "*.md", run = "glow" },
# Archive previewer
	{ mime = "application/*zip",            run = "ouch" },
	{ mime = "application/x-tar",           run = "ouch" },
	{ mime = "application/x-bzip2",         run = "ouch" },
	{ mime = "application/x-7z-compressed", run = "ouch" },
	{ mime = "application/x-rar",           run = "ouch" },
	{ mime = "application/x-xz",            run = "ouch" },
	{ mime = "application/xz",              run = "ouch" },
]
[opener]
extract = [
	{ run = 'ouch d -y "$@"', desc = "Extract here with ouch" },
]
edit = [
	{ run = '${EDITOR:-vi} "$@"', desc = "Edit", block = true, for = "unix" },
]
vim = [
	{ run = 'vim "$0"', desc = "Vim", block = true},
]
open = [
	{ run = 'xdg-open "$1"', desc = "Open" },
]
view = [
	{ run = 'geeqie "$1"', desc = "View" },
]
play = [
	{ run = 'mpv --force-window "$@"', orphan = true, desc = "Play" },
]
kate = [
	{ run = 'kate "$0"', orphan = true, desc = "Kate" },
]
[open]
rules = [
	# Folder
	{ name = "*/", use = [ "open", "reveal" ] },
	# Text"edit",
	{ mime = "text/*", use = [ "edit", "reveal", "kate", "vim" ] },
	# Image
	{ mime = "image/*", use = [ "view", "reveal" ] },
	# Media
	{ mime = "{audio,video}/*", use = [ "play", "reveal" ] },
	# Archive
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [ "extract", "reveal" ] },
	# JSON
	{ mime = "application/{json,ndjson}", use = [ "edit", "reveal" ] },
	{ mime = "*/javascript", use = [ "edit", "reveal" ] },
	# Empty file
	{ mime = "inode/empty", use = [ "edit", "reveal" ] },
	# Fallback
	{ name = "*", use = [ "open", "reveal" ] },
]
