#!/usr/bin/env bash
JUNKLIST=${XDG_CONFIG_HOME:-.config}/applauncher-dejunker/junklist.txt

case "$1" in
    help)
    echo -e "appjunk: Removes all .desktop entries listed for junking"
    echo -e "appjunk list junk: Displays apps listed for junking"
    echo -e "appjunk list known: Displays apps NOT listed for junking"
    echo -e "appjunk list add [.DESKTOP ENTRY]: adds an entry to the junk list"
    echo -e "appjunk list unjunk [.DESKTOP ENTRY]: removes an entry from the junk list"
    ;;
    "")
        xargs -a "$JUNKLIST" -I{} rm /usr/share/applications/{}
    ;;
    list)
        case "$2" in
        junk)
            xargs -a "$JUNKLIST" -n 1
        ;;
        known)
            ls /usr/share/applications
        ;;
        add)
            if [ -z "$3" ]; then
                echo "you didn't say which .desktop, birdbrain" >&2
            else
                if grep -q "$3" "$JUNKLIST"; then
                    echo "it already exists, dingus" >&2
                else
                    echo "$3" >> "$JUNKLIST"
                fi
            fi
        ;;
        unjunk)
        if [ -z "$2" ]; then
            echo "you didn't say which .desktop, birdbrain" >&2
        else
            if grep -q "$2" "$JUNKLIST"; then
                echo "it doesn't exist, what are you doinggg?" >&2
            else
                grep -v "$2" "$JUNKLIST" > temp && mv temp "$JUNKLIST"
            fi
        fi
        ;;
        esac
esac
