#!/bin/bash

WINDOW_ID=$(xdotool getactivewindow)       #gets the ID of this terminal window
wmctrl -i -r $WINDOW_ID -b add,above       #keeps terminal window on top

bootlist() { #launch each program in the background, disconnected from the terminal

    nohup discord &
    nohup qbitorrent &
    bluetoothctl connect 28:11:A5:72:F0:1E # connects to Jupiter of the Monkey
	pw-cli s 56 Profile '{ index: 5, save: true }' # Connects to the correct audio profile
}

extended-bootlist() {
    gsettings set org.cinnamon.desktop.default-applications.terminal exec /usr/bin/kitty #sets default terminal to kitty
    gsettings set org.cinnamon.desktop.peripherals.keyboard repeat true #makes sure holding keyboard keys results in repeated input
}

quit(){     #unlocking the window and prompting to exit
    sleep 0.5
    read -s -p "Press any key to exit..."
    wmctrl -ir $WINDOW_ID -b remove,above #stops terminal window from being always-on top
    echo ""
    exit
}

prompt() { #the whole y/n prompt
    read -p "> Initiate boot sequence? [Y/n]: " answer
    answer=${answer,,}
    if [ "$answer" == "n" ]; then #answer is no, proceeds to quit
        echo -e "\n<Boot sequence aborted>\n\n> Use 'bootseq' to manually initiate boot sequence\n"
        quit
    elif [ "$answer" == "y" ]; then #answers is yes, proceeds to initiate boot sequence
        bootseq
    else
        echo "> Invalid input, Please select 'y' or 'n'" #recursively prompts for valid input
        prompt
    fi
}


bootseq() { #all the fanfare and ui around making the bootlist boot
    unimatrix -s 99 -a -c magenta -f &     #runs the matrix visuals
    UNIMATRIX_PID=$!        #get unimatrix's process ID

    bootlist #boots all the software in bootlist()

    sleep 0.7
    kill $UNIMATRIX_PID
    wait $UNIMATRIX_PID 2>/dev/null #the machine told me to
    clear
}

while getopts ":y:h:e" opt; do #run modifiers.
    case ${opt} in
        y) #run to skip the prompt
            bootseq
            echo -e "\n<Boot sequence complete>\n"
            quit
            ;;
        h)
            echo -e "-y    skips the y/n prompt\n-h    displays this help messege"
            quit
            ;;
        e)
            extended-bootlist
            bootseq
            echo -e "\n<EXTENDED BOOT SEQUENCE DEPLOYED>\n"
            quit
            ;;
        :)
            ;;
        \?)
            echo "> invalid option"
            ;;

    esac
done
prompt #recursive thing- the program actually starts here :3
