#!/usr/bin/env bash

case "$1" in
    bind)
        if [ -z "$2" ]; then
            echo -e "\e[31mName the daemon you wish to bind to your service, oh mistress.\e[0m" >&2
        else
            if [ -e /etc/sv/"$1" ]; then
                sudo ln -s /etc/sv/"$1" /var/service/
                echo -e "\e[33m$1\e[36m is bound to your service, lady witch.\e[0m"
            else
                echo -e "\e[36m\"$1\"\e[31m does not exist in any codecies we posess, o witch\e[0m" >&2
            fi
        fi
    ;;
    list)
        case "$2" in
            active)
                sv s /var/service/*
            ;;
            available)
                ls -1 /etc/sv/
            ;;
            *)
            echo -e "\e[36mI may \e[33mlist active\e[36m daemons, or I could \e[33mlist available\e[36m daemons."
        esac
    ;;
esac
