#!/usr/bin/env bash
temp=/tmp/fetchmethemoon.txt
info=./details
chmod 755 $temp
phoon -q > $temp
#phoon -q
linecount=/tmp/linecount
awk '{print length($0)}' $temp > $linecount
awk '{print}' $linecount > $temp
echo -e "\033[23A\033[2B"

for i in $(seq 0 "$(wc -l $info | cut -f1 -d' ')"); do #find how many lines in details.txt
    line=$(sed -n $((i+2))p $temp) #find the right line on the moon (2 from top)
    echo -en "\033[$((line+3))C" # move the right distance across the moon
    sed -n "${i}p" $info #print the line
done
#   we now intrrupt your regularly schedule queer bashing to bring you: ✨assembler✨
infolength=$(wc -l $info | cut -f1 -d ' ')
moonlength=$(wc -l $temp | cut -f1 -d ' ')
jumpspace=$(($moonlength-$infolength))
echo -e "\033[${jumpspace}B"
