#!/usr/bin/env bash
temp=/tmp/fetchmethemoon.txt
chmod 755 $temp
phoon -q > $temp
phoon -q
linecount=/tmp/linecount
awk '{print length($0)}' $temp > $linecount
awk '{print}' $linecount > $temp
echo -e "\033[23A"
line=$(awk 'NR==2' $temp)
echo -en "\033[$((line+3))C"
echo -e "\033[33mOS: \033[32m \033[37mVoid Linux"
line=$(awk 'NR==3' $temp)
echo -en "\033[$((line+3))C"
echo -e "\033[33mFont: \033[37mProggyClean SZ"
echo
line=$(awk 'NR==5' $temp)
echo -en "\033[$((line+4))C"
for i in {30..37}; do
    echo -en "\033[${i}m██"
done
echo
echo -en "\033[$((line+4))C"
for i in {90..97}; do
    echo -en "\033[${i}m██"
done
echo -e "\033[21B"


