#!/bin/bash
#xdotool search GUILTY windowactivate #swaps to the GGST window

#xdotool keyup ALT
xdotool type d
# xdotool key d+s
# xdotool key s
# xdotool key s+a
# xdotool key a
# xdotool key x

sleep 1
#DSADZ



