- host:
    address: irregularnotes.local
    description: Desktop
    group: Home
    title: IrregularNotes
- host:
    address: hachiko.local
    description: Personal server
    group: Home
    title: Hachiko
- host:
    address: twister.local
    description: Laptop
    title: Twister
- host:
    address: pablotronica.local
    description: Off-site laptop
    group: Off-site
    title: Pablotronica
- host:
    address: terminal-c.local
    description: TV client PC
    group: Home
    title: Terminal-C
