return {
  "nvim-treesitter/nvim-treesitter",
  branch = "master",
  lazy = false,
  build = ":TSUpdate",
  opts = {
    highlight = { enable = true },
    indent = { enable = true },
    ensure_installed = {
      "bash",
      "caddy",
      "css",
      "csv",
      "desktop",
      "diff",
      "dockerfile",
      "html",
      "java",
      "javascript",
      "jq",
      "json",
      "lua",
      "markdown",
      "markdown_inline",
      "printf",
      "python",
      "qmldir",
      "qmljs",
      "regex",
      "scss",
      "sql",
      "toml",
      "typst",
      "sway",
      "xml",
      "yaml",
      "vim",
    },
    auto_install = true,
  },
}
