return  {
    "nvim-treesitter/nvim-treesitter", 
    branch = 'master', 
    lazy = false, 
    build = ":TSUpdate",
    opts = {
        highlight = { enable = true },
        indent = { enable = true },
        ensure_installed = {
            "bash",
            "caddy",
            "css",
            "csv",
            "desktop",
            "dockerfile",
            "html",
            "java",
            "javascript",
            "jq",
            "json",
            "lua",
            "markdown",
            "python",
            "qmldir",
            "qmljs",
            "regex",
            "scss",
            "sql",
            "sway",
            "toml",
            "yaml",
        },
        auto_install = true,
    },
}
