#!/bin/bash
for FILE in *; do
   if [[ "$FILE" == *.mkv ]]; then
      if [[ "$FILE" == "[SubsPlease]"* || "$FILE" == "[Erai-raws]"* ]]; then
      RENAME="${FILE//[^a-zA-Z0-9 -]/}"
      RENAME="${RENAME#Erai-raws }";RENAME="${RENAME#SubsPlease }"
      RENAME="${RENAME%% 1080p*}".mkv
      RENAME="${RENAME// /-}"
      mv "$FILE" "$RENAME"
      fi
   fi
done
